name: ankh-groovy
version: 1.0-SNAPSHOT
api-version: 1.16
main: org.inksnow.ankh.groovy.AnkhGroovyPlugin
load: STARTUP
authors:
  - InkerBot
depend:
  - ankh-core

ankh-classpath:
  "groovy.": SELF_ONLY
  "groovyjarjarantlr4.": SELF_ONLY
  "groovyjarjarasm.": SELF_ONLY
  "groovyjarjarpicocli.": SELF_ONLY
  "org.apache.groovy.": SELF_ONLY
  "org.codehaus.groovy.": SELF_ONLY